name: deploy-to-github-pages
on:
  push:
    branches:
      - main
jobs:
  deploy_to_gh_pages:
    runs-on: ubuntu-latest
    env:
      DEPLOY_BRANCH: main
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy public dir
        run: |
          touch public/.nojekyll
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f public
          git commit -m "Hugo build and deploy from Github workflows"
          git push -u origin `git subtree split --prefix public $DEPLOY_BRANCH`:refs/heads/gh-pages --force